### PR TITLE
Minor formatting proposal (added markdown style formatting)

### PR DESCRIPTION
**Pull request by kant**

### CODE REVIEW

**Comment by raynamharris** [comment]
Thanks @kant . I'm not sure about this one.... It seems like the aio.md file in this repo is a little out of date with the source code [aio file in the styles repo](https://github.com/carpentries/styles/blob/gh-pages/aio.md) and the [styles-es repo](https://github.com/carpentries/styles-es) doesn't have an aio file. Maybe @fmichonneau can advise.

**Comment by fmichonneau** [comment]
for historical reasons `aio.md` used to be in the `bin/boilerplate/` folder and needed to be copied manually at the root of the repository. It's now at the root of the repository, so if you want to pull the latest version of the template it will be in the right location. 

@kant, what issue are you trying to solve with this PR?

**Comment by kant** [comment]
@fmichonneau The title of PR tells all about, this is a minor proposal for the sake of cleanliness

**Comment by fmichonneau** [comment]
the code on this page is actually javascript intended to be executed by the web browser to pull the content from all the episodes into a single page. By adding the tickmarks, the empty YAML header isn't complete anymore and I'm afraid the script will be broken.

**Comment by kant** [comment]
@fmichonneau You are right!

**Pull request closed without merging**
