### PR TITLE
Update to styles v9.5.2

### PR DESCRIPTION
**Pull request by fmichonneau**
This pull request brings the latest version of the template to this repository. Release notes are available from the styles GitHub Repository. See [v9.5.1](https://github.com/carpentries/styles/releases/tag/v9.5.1) and [v9.5.2](https://github.com/carpentries/styles/releases/tag/v9.5.2). Deployment progress tracked in carpentries/styles#302.

### CODE REVIEW

**Comment by raynamharris** [comment]
@fmichonneau how come the commits in this PR are very different from those in https://github.com/swcarpentry/git-novice-es/pull/71 and https://github.com/swcarpentry/r-novice-gapminder-es/pull/86?

screen shot 2018-06-20 at 5 05 01 pm

**Comment by fmichonneau** [comment]
It is because they don't share the same starting point in their history. If you look at the bottom you'll see that they end up at the same point (555226b) with a few commits that are specific to each repository after that.

**Comment by raynamharris** [comment]
Okay then. I'm ready to merge if you are!

**Comment by fmichonneau** [comment]
thanks, all merged!

**Pull request merged**
